import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/**
 * DESCRIZIONE PRELIMINARE:
 * Il file `app/layout.tsx` è il contenitore principale di tutta l'applicazione
 * Next.js. Definisce la struttura base HTML (tag <html> e <body>) che viene
 * mantenuta identica su ogni pagina, simulando un template tradizionale. 
 * È il punto di partenza per il rendering, garantendo la coerenza visiva e 
 * permettendo di importare qui le configurazioni globali (come i font o gli stili CSS).
 */

const geistSans = Geist({ //* impostazioni per i font sans-serif */
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({ //* impostazioni per i font monospace */
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = { //* metadati per la pagina */
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ //* definisce la struttura base HTML */
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
